"""Tools for decoding Civilization V save-file structures."""

from .civ5_header import Civ5SaveHeaderDecodeError, decode_civ5_save_header
from .civ5_header_types import (
    ArchiveGameMode,
    BaseInfo,
    Civ5SaveHeader,
    ClimateInfo,
    CompressedChunk,
    CustomOption,
    EnabledDlc,
    EnabledMod,
    GameMapType,
    PlayerSlot,
    PreGameArchive,
    QuickGameMode,
    QuickHeader,
    SeaLevelInfo,
    SlotClaim,
    SlotHints,
    SlotStatus,
    TurnTimerInfo,
    UnknownHeaderSpan,
    WorldInfo,
)
from .cv_plot import CvPlotDecodeError, decode_cv_plot_array
from .cv_plot_types import (
    ArchaeologyData,
    BuildProgress,
    CvPlot,
    FlowDirection,
    HashedType,
    ObjectReference,
    PlotFlags,
    PlotType,
    PlotYields,
    RouteType,
    TerrainType,
)

__all__ = (
    "ArchaeologyData",
    "ArchiveGameMode",
    "BaseInfo",
    "BuildProgress",
    "Civ5SaveHeader",
    "Civ5SaveHeaderDecodeError",
    "ClimateInfo",
    "CompressedChunk",
    "CustomOption",
    "CvPlot",
    "CvPlotDecodeError",
    "EnabledDlc",
    "EnabledMod",
    "FlowDirection",
    "GameMapType",
    "HashedType",
    "ObjectReference",
    "PlayerSlot",
    "PlotFlags",
    "PlotType",
    "PlotYields",
    "PreGameArchive",
    "QuickGameMode",
    "QuickHeader",
    "RouteType",
    "SeaLevelInfo",
    "SlotClaim",
    "SlotHints",
    "SlotStatus",
    "TerrainType",
    "TurnTimerInfo",
    "UnknownHeaderSpan",
    "WorldInfo",
    "decode_civ5_save_header",
    "decode_cv_plot_array",
)
